version: '3'

services:
  api-kit:
    build: .
    container_name: api-kit
    volumes:
      - ../:/api-kit
    networks:
      - api-kit
    command: bash
    stdin_open: true
    tty: true
    restart: 'no'

networks:
  api-kit:
    driver: bridge
